fix javadocs for telemetry core
newrelic/newrelic-telemetry-sdk-java pull request #241
Opened 2020-10-01 21:40 UTC by uaihebert

2020-10-05 17:45 UTC, uaihebert commented
After this PR gets merged, I will work on the last one.

2020-10-05 20:57 UTC, breedx-nr commented on telemetry_core/src/main/java/com/newrelic/telemetry/events/Event.java
> +   * @param timestamp time stamp in epoch
millis?

2020-10-05 20:59 UTC, breedx-nr requested changes
Looks good, let's just change that one timestamp to clarify units.  Thanks again!

2020-10-05 21:00 UTC, breedx-nr commented
(Also needs a rebase)

2020-10-05 21:34 UTC, uaihebert commented
all done. ( :

2020-10-06 20:18 UTC, breedx-nr approved these changes

2020-10-06 20:19 UTC, breedx-nr commented
Thanks again @uaihebert !

2020-10-06 20:19 UTC, merged