Added EU endpoint support in SenderConfiguration and the BatchSenders for Metric, Log, and Trace data types.
newrelic/newrelic-telemetry-sdk-java pull request #276
Opened 2021-06-11 22:09 UTC by yamnihcg

2021-06-21 17:58 UTC, XiXiaPdx requested changes
Looking great! A few more tests, now that user can override region with endpoint

2021-06-21 17:58 UTC, XiXiaPdx commented on telemetry-core/src/main/java/com/newrelic/telemetry/SenderConfiguration.java
> +  public boolean isUserProvideEndpoint() {
nitpick spelling - `isUserProvidedEnpoint()`

2021-06-21 17:58 UTC, XiXiaPdx commented on telemetry-core/src/main/java/com/newrelic/telemetry/metrics/MetricBatchSender.java
> +        url = new URL(EUROPEAN_URL + METRICS_PATH);
Can we make the creation of the Default URL be simple and consistent with the creation of the European Url?

2021-06-21 17:58 UTC, XiXiaPdx commented on telemetry-core/src/main/java/com/newrelic/telemetry/SenderConfiguration.java
> +      SenderConfiguration.userProvidedEndpoint = true;
please provide a test that userProvidedEndpoint will be set to true

2021-06-21 17:58 UTC, XiXiaPdx commented on telemetry-core/src/main/java/com/newrelic/telemetry/events/EventBatchSender.java
> +    if (isCustomEndpoint == true) {
please add a test in each BatchSender to confirm custom endpoint will override region

2021-06-25 19:29 UTC, XiXiaPdx requested changes
just a few items left. Thank you!

2021-06-25 19:29 UTC, XiXiaPdx commented on telemetry-core/src/main/java/com/newrelic/telemetry/SenderConfiguration.java
> +      // Add IllegalArgumentException if region isn't US or EU
remove this comment plz

2021-06-25 19:29 UTC, XiXiaPdx commented on telemetry-core/src/test/java/com/newrelic/telemetry/SenderConfigurationTest.java
> +  void defaultEndpointAsStringTest() throws Exception {
I think this test just confirms `toString()` works? If. so, this test can be removed.

2021-06-25 19:29 UTC, XiXiaPdx commented on telemetry-core/src/test/java/com/newrelic/telemetry/SenderConfigurationTest.java
> +  void userEndpointAsStringTest() throws Exception {
same for this test, I think it can be removed

2021-06-25 23:04 UTC, yamnihcg commented
EventBatchSender:

Default (to US Prod, US License Key): Successful 
Set Region (to US Prod, US License Key): Successful
Set Region (to EU Prod, EU License Key): Successful 
User Provided Endpoint: Successful

MetricBatchSender:

Default (to US Prod, US License Key): Successful
Set Region (to US Prod, US License Key): Successful
Set Region (to EU Prod, EU License Key): Successful
User Provided Endpoint: Successful

LogBatchSender:

Default (to US Prod, US License Key): Successful
Set Region (to US Prod, US License Key): Successful
Set Region (to EU Prod, EU License Key): Successful
User Provided Endpoint: Successful

SpanBatchSender:

Default (to US Prod, US License Key): Successful
Set Region (to US Prod, US License Key): Successful
Set Region (to EU Prod, EU License Key): Successful
User Provided Endpoint: Successful

2021-06-28 16:50 UTC, XiXiaPdx approved these changes

2021-06-28 16:51 UTC, XiXiaPdx commented
This looks great @yamnihcg  and thank you for persistently chipping away at this! 🚀 🚀

2021-06-28 17:10 UTC, merged